//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-RUL1LBP2\\SQLEXPRESS;Initial Catalog=DA_QL_KTX1;Persist Securit" +
            "y Info=True;User ID=sa;Password=123;TrustServerCertificate=True")]
        public string DA_QL_KTX1ConnectionString {
            get {
                return ((string)(this["DA_QL_KTX1ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-RUL1LBP2\\SQLEXPRESS;Initial Catalog=DA_QL_KTX2;Persist Securit" +
            "y Info=True;User ID=sa;Password=123;Encrypt=True;TrustServerCertificate=True")]
        public string DA_QL_KTX2ConnectionString {
            get {
                return ((string)(this["DA_QL_KTX2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-RUL1LBP2\\SQLEXPRESS;Initial Catalog=DA_QL_KTX2;User ID=sa;Pass" +
            "word=123;TrustServerCertificate=True")]
        public string DA_QL_KTX2ConnectionString1 {
            get {
                return ((string)(this["DA_QL_KTX2ConnectionString1"]));
            }
        }
    }
}
