#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DA_QL_KTX")]
	public partial class DA_QL_KTXDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertLoaiNoiQuy(LoaiNoiQuy instance);
    partial void UpdateLoaiNoiQuy(LoaiNoiQuy instance);
    partial void DeleteLoaiNoiQuy(LoaiNoiQuy instance);
    partial void InsertNoiQuy(NoiQuy instance);
    partial void UpdateNoiQuy(NoiQuy instance);
    partial void DeleteNoiQuy(NoiQuy instance);
    #endregion
		
		public DA_QL_KTXDataContext() : 
				base(global::DTO.Properties.Settings.Default.DA_QL_KTXConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DA_QL_KTXDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DA_QL_KTXDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DA_QL_KTXDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DA_QL_KTXDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<LoaiNoiQuy> LoaiNoiQuys
		{
			get
			{
				return this.GetTable<LoaiNoiQuy>();
			}
		}
		
		public System.Data.Linq.Table<NoiQuy> NoiQuys
		{
			get
			{
				return this.GetTable<NoiQuy>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiNoiQuy")]
	public partial class LoaiNoiQuy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaLoaiNQ;
		
		private string _TenLoaiNQ;
		
		private string _MoTa;
		
		private EntitySet<NoiQuy> _NoiQuys;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiNQChanging(int value);
    partial void OnMaLoaiNQChanged();
    partial void OnTenLoaiNQChanging(string value);
    partial void OnTenLoaiNQChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    #endregion
		
		public LoaiNoiQuy()
		{
			this._NoiQuys = new EntitySet<NoiQuy>(new Action<NoiQuy>(this.attach_NoiQuys), new Action<NoiQuy>(this.detach_NoiQuys));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiNQ", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaLoaiNQ
		{
			get
			{
				return this._MaLoaiNQ;
			}
			set
			{
				if ((this._MaLoaiNQ != value))
				{
					this.OnMaLoaiNQChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiNQ = value;
					this.SendPropertyChanged("MaLoaiNQ");
					this.OnMaLoaiNQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiNQ", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string TenLoaiNQ
		{
			get
			{
				return this._TenLoaiNQ;
			}
			set
			{
				if ((this._TenLoaiNQ != value))
				{
					this.OnTenLoaiNQChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiNQ = value;
					this.SendPropertyChanged("TenLoaiNQ");
					this.OnTenLoaiNQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiNoiQuy_NoiQuy", Storage="_NoiQuys", ThisKey="MaLoaiNQ", OtherKey="MaLoaiNQ")]
		public EntitySet<NoiQuy> NoiQuys
		{
			get
			{
				return this._NoiQuys;
			}
			set
			{
				this._NoiQuys.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NoiQuys(NoiQuy entity)
		{
			this.SendPropertyChanging();
			entity.LoaiNoiQuy = this;
		}
		
		private void detach_NoiQuys(NoiQuy entity)
		{
			this.SendPropertyChanging();
			entity.LoaiNoiQuy = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NoiQuy")]
	public partial class NoiQuy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNoiQuy;
		
		private string _TenNoiQuy;
		
		private System.Nullable<decimal> _MucPhatTien;
		
		private string _HinhThucXL;
		
		private int _MaLoaiNQ;
		
		private EntityRef<LoaiNoiQuy> _LoaiNoiQuy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNoiQuyChanging(int value);
    partial void OnMaNoiQuyChanged();
    partial void OnTenNoiQuyChanging(string value);
    partial void OnTenNoiQuyChanged();
    partial void OnMucPhatTienChanging(System.Nullable<decimal> value);
    partial void OnMucPhatTienChanged();
    partial void OnHinhThucXLChanging(string value);
    partial void OnHinhThucXLChanged();
    partial void OnMaLoaiNQChanging(int value);
    partial void OnMaLoaiNQChanged();
    #endregion
		
		public NoiQuy()
		{
			this._LoaiNoiQuy = default(EntityRef<LoaiNoiQuy>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNoiQuy", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaNoiQuy
		{
			get
			{
				return this._MaNoiQuy;
			}
			set
			{
				if ((this._MaNoiQuy != value))
				{
					this.OnMaNoiQuyChanging(value);
					this.SendPropertyChanging();
					this._MaNoiQuy = value;
					this.SendPropertyChanged("MaNoiQuy");
					this.OnMaNoiQuyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNoiQuy", DbType="NVarChar(255)")]
		public string TenNoiQuy
		{
			get
			{
				return this._TenNoiQuy;
			}
			set
			{
				if ((this._TenNoiQuy != value))
				{
					this.OnTenNoiQuyChanging(value);
					this.SendPropertyChanging();
					this._TenNoiQuy = value;
					this.SendPropertyChanged("TenNoiQuy");
					this.OnTenNoiQuyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MucPhatTien", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> MucPhatTien
		{
			get
			{
				return this._MucPhatTien;
			}
			set
			{
				if ((this._MucPhatTien != value))
				{
					this.OnMucPhatTienChanging(value);
					this.SendPropertyChanging();
					this._MucPhatTien = value;
					this.SendPropertyChanged("MucPhatTien");
					this.OnMucPhatTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhThucXL", DbType="NVarChar(255)")]
		public string HinhThucXL
		{
			get
			{
				return this._HinhThucXL;
			}
			set
			{
				if ((this._HinhThucXL != value))
				{
					this.OnHinhThucXLChanging(value);
					this.SendPropertyChanging();
					this._HinhThucXL = value;
					this.SendPropertyChanged("HinhThucXL");
					this.OnHinhThucXLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiNQ", DbType="Int NOT NULL")]
		public int MaLoaiNQ
		{
			get
			{
				return this._MaLoaiNQ;
			}
			set
			{
				if ((this._MaLoaiNQ != value))
				{
					if (this._LoaiNoiQuy.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiNQChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiNQ = value;
					this.SendPropertyChanged("MaLoaiNQ");
					this.OnMaLoaiNQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiNoiQuy_NoiQuy", Storage="_LoaiNoiQuy", ThisKey="MaLoaiNQ", OtherKey="MaLoaiNQ", IsForeignKey=true)]
		public LoaiNoiQuy LoaiNoiQuy
		{
			get
			{
				return this._LoaiNoiQuy.Entity;
			}
			set
			{
				LoaiNoiQuy previousValue = this._LoaiNoiQuy.Entity;
				if (((previousValue != value) 
							|| (this._LoaiNoiQuy.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiNoiQuy.Entity = null;
						previousValue.NoiQuys.Remove(this);
					}
					this._LoaiNoiQuy.Entity = value;
					if ((value != null))
					{
						value.NoiQuys.Add(this);
						this._MaLoaiNQ = value.MaLoaiNQ;
					}
					else
					{
						this._MaLoaiNQ = default(int);
					}
					this.SendPropertyChanged("LoaiNoiQuy");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
