<?xml version="1.0" encoding="utf-8"?><Database Name="DA_QL_KTX2" Class="QLKTXDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-RUL1LBP2\SQLEXPRESS;Initial Catalog=DA_QL_KTX2;User ID=sa;Trust Server Certificate=True" SettingsObjectName="DTO.Properties.Settings" SettingsPropertyName="DA_QL_KTX2ConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.LoaiPhong" Member="LoaiPhongs">
    <Type Name="LoaiPhong">
      <Column Name="MaLoaiPhong" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoaiPhong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LoaiPhong_Phong" Member="Phongs" ThisKey="MaLoaiPhong" OtherKey="MaLoaiPhong" Type="Phong" />
    </Type>
  </Table>
  <Table Name="dbo.DangKyPhong" Member="DangKyPhongs">
    <Type Name="DangKyPhong">
      <Column Name="MaDangKyPhong" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaPhong" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MaSinhVien" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="NgayDK" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NgayBD" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NgayKT" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Giuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Tang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NguyenVong1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NguyenVong2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="Phong_DangKyPhong" Member="Phong" ThisKey="MaPhong" OtherKey="MaPhong" Type="Phong" IsForeignKey="true" />
      <Association Name="SinhVien_DangKyPhong" Member="SinhVien" ThisKey="MaSinhVien" OtherKey="MaSinhVien" Type="SinhVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="MaNhanVien" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ChucVu" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChiLienLac" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MaTaiKhoan" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Phong" Member="Phongs">
    <Type Name="Phong">
      <Column Name="MaPhong" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaLoaiPhong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoLuongSinhVienToiDa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TrangThai" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MaDienNuoc" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Association Name="Phong_DangKyPhong" Member="DangKyPhongs" ThisKey="MaPhong" OtherKey="MaPhong" Type="DangKyPhong" />
      <Association Name="LoaiPhong_Phong" Member="LoaiPhong" ThisKey="MaLoaiPhong" OtherKey="MaLoaiPhong" Type="LoaiPhong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SinhVien" Member="SinhViens">
    <Type Name="SinhVien">
      <Column Name="MaSinhVien" Type="System.String" DbType="VarChar(12) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TruongPhong" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="NoiSinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HoKhauThuongTru" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CCCD" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="HinhNhanDien" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="HinhCCCDTruoc" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="HinhCCCDSau" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Association Name="SinhVien_DangKyPhong" Member="DangKyPhongs" ThisKey="MaSinhVien" OtherKey="MaSinhVien" Type="DangKyPhong" />
    </Type>
  </Table>
</Database>